# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B6S4abmyqV08vmm8ztgBzA2euZ_51dqc
"""

from flask import Flask, request, render_template
import google.generativeai as palm

palm.configure(api_key="AIzaSyBKkR_J1ixzCZcWTCsidT9caTHanESD_CM")
model = {"model":"models/chat-bison-001"}


app = Flask(__name__)
@app.route("/",methods=['GET','POST'])
#app.route is a decorator
def index():
    if request.method=='POST':
        q = request.form.get("q")
        print(q)
        r = palm.chat(
            **model,
            messages = q
        )
        return (render_template("index.html", result=r.last))
    else:
        return (render_template('index.html',result="waiting for question...."))
if __name__ == "__main__":
    app.run()